blank_issues_enabled: false
contact_links:
  - name: 💬 Mneme Discussions
    url: https://github.com/magesguild/mneme/discussions
    about: For support, troubleshooting, how-to questions, and project discussion.
